# Generated by Django 3.2.6 on 2021-08-08 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Arms', 'Arms'), ('Abdominals', 'Abdominals'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Cardio', 'Cardio')], max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('schema', models.ImageField(upload_to='schema')),
                ('series', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_workout_app.workout')),
            ],
        ),
    ]
